const EVENT_ORDER_CREATED = 1;
const EVENT_ORDER_CANCELLED = 2;
const EVENT_ORDER_DRIVER_ACCEPTED = 3;
const EVENT_ORDER_DRIVER_PICKED_UP = 4;
const EVENT_ORDER_DELIVERED = 5;
const EVENT_USER_DEVICE_NEW = 6;
